
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./font.css";
import './globals.css'


import { cookies } from "next/headers"
import { jwtVerify } from "jose"
import NavWrapper from "./NavbarWrapper"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 











export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const token = cookieStore.get("token")?.value
  
  let islogged = false
  if (token) {
    try {
      const secret = new TextEncoder().encode(process.env.JWT_SECRET)
      await jwtVerify(token, secret)
      islogged = true
    } catch(err) {
      islogged = false
    }
  }

  return (
    <html lang="en">
      <body>
        
          <NavWrapper islogged={islogged} />
          <main className="min-w-full min-h-screen">
            {children}
          </main>
        
      </body>
    </html>
  )
}